//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeenieFab.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class WeenieFabUser : global::System.Configuration.ApplicationSettingsBase {
        
        private static WeenieFabUser defaultInstance = ((WeenieFabUser)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new WeenieFabUser())));
        
        public static WeenieFabUser Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string DefaultSqlPath {
            get {
                return ((string)(this["DefaultSqlPath"]));
            }
            set {
                this["DefaultSqlPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string DefaultJsonPath {
            get {
                return ((string)(this["DefaultJsonPath"]));
            }
            set {
                this["DefaultJsonPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string DefaultESPath {
            get {
                return ((string)(this["DefaultESPath"]));
            }
            set {
                this["DefaultESPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoLoadESFiles {
            get {
                return ((bool)(this["AutoLoadESFiles"]));
            }
            set {
                this["AutoLoadESFiles"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseFilePaths
        {
            get
            {
                return ((bool)(this["UseFilePaths"]));
            }
            set
            {
                this["UseFilePaths"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoCalcHealth {
            get {
                return ((bool)(this["AutoCalcHealth"]));
            }
            set {
                this["AutoCalcHealth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoCalcSkill {
            get {
                return ((bool)(this["AutoCalcSkill"]));
            }
            set {
                this["AutoCalcSkill"] = value;
            }
        }
    }
}
